#!/usr/bin/python

import sys
sys.path.append('./')

from base_test import BaseTest
           
def test_cleanup_nova_instance_user(username, password, tenant_name, server_name):
    """ test administrator to teminate a server created by a user """

    user_bt = BaseTest(username, password, tenant_name)
    server = user_bt.get_server_by_name(server_name)

    bt = BaseTest()
    response, content = bt.servers_client.delete_server(server['id'])

    if response['status'] == '204':
        return 0
    return 1

ret = test_cleanup_nova_instance_user('test_create_user', 'crowbar', 'test_create_tenant', 'jeos_01')
exit(ret)
